 services:
  - type: web
    name: career-intelligence
    runtime: python
    repo: https://github.com/Fadel333/career-intelligence
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true