"""Add CV analysis fields to User model

Revision ID: 4506ac820f11
Revises: 
Create Date: 2026-07-02 20:10:54.607596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4506ac820f11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('portfolio_url', sa.String(length=255), nullable=True),
    sa.Column('current_job', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cv_analysis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cv_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cv_uploaded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('employability_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('detected_sector', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('detected_sector')
        batch_op.drop_column('employability_score')
        batch_op.drop_column('cv_uploaded_at')
        batch_op.drop_column('cv_filename')
        batch_op.drop_column('cv_analysis')
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('phone')
        batch_op.drop_column('location')
        batch_op.drop_column('bio')
        batch_op.drop_column('profile_image')

    op.drop_table('profiles')
    # ### end Alembic commands ###
