"""Add retention_days to users and recruiter_profiles

Revision ID: 7b3c39758129
Revises: 43c559c4ca09
Create Date: 2026-07-19 12:06:57.125150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3c39758129'
down_revision = '43c559c4ca09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('recruiter_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retention_days', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retention_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('retention_days')

    with op.batch_alter_table('recruiter_profiles', schema=None) as batch_op:
        batch_op.drop_column('retention_days')

    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
