"""Add interview practice tables

Revision ID: b19152fe3fec
Revises: 85539d9af13a
Create Date: 2026-07-21 16:12:12.150417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19152fe3fec'
down_revision = '85539d9af13a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_practices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('question_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('tips', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['interview_practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('time_taken', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('improvements', sa.JSON(), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['interview_practices.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_responses')
    op.drop_table('interview_questions')
    op.drop_table('interview_practices')
    # ### end Alembic commands ###
