"""Add cv_path column to candidates

Revision ID: b6cdefa32681
Revises: 0a69bb6b2b7d
Create Date: 2026-08-01 21:10:53.113604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6cdefa32681'
down_revision = '0a69bb6b2b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('cv_path')

    # ### end Alembic commands ###
